<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MoviesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('movies')->delete();
        
        \DB::table('movies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Our Beloved Summer',
                'description' => 'Our Beloved Summer KDrama adalah sebuah komedi romantis yang menggambarkan dua mantan kekasih yang berpisah 10 tahun yang lalu. Choi Woong adalah ilustrator berjiwa bebas dengan kepribadian yang belum dewasa namun tulus. Gook Yeon Soo adalah seorang ahli PR yang mencoba untuk hidup secara realistis sebagai orang dewasa. Mereka dulunya menjalin hubungan romantis tetapi kemudian mereka berjanji untuk tidak bertemu lagi di masa depan. Namun, nasib lain menyatukan mereka ketika film dokumenter sekolah menengah mereka menjadi viral.',
                'show_date' => 'Dec 6, 2021 - Jan 25, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Yoon Jin',
                'artist' => 'Ahn Dong Goo, Choi Woo Shik, Kim Da Mi, Kim Sung Chul, Park Won Sang, Roh Jeong Eui',
                'episode' => 16,
                'slug' => 'our-beloved-summer',
                'image' => 'https://i.mydramalist.com/4QLgQ_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Happiness',
                'description' => 'Sebuah thriller apokaliptik yang mengambil sekitar di saat penyakit menular telah muncul sebagai normal baru.Di sebuah kondominium yang baru dibangun di kota besar di mana lantai yang lebih baik untuk pendapatan trendi dan lantai yang lebih rendah disewakan, drama ini menggambarkan perjuangan mental yang tersebar dan diskriminasi keanggunan yang terjadi. Metropolis mencapai titik terendah ketika kiamat yang mendekat menghantam dalam bentuk gangguan menular jenis baru di mana orang-orang menderita rasa haus yang tak kunjung reda.Yoon Sae Bom tumbuh dalam keluarga yang tidak bahagia. Dia tegas dan memiliki penilaian yang cepat, dan dia adalah tipe orang yang menggerakkan segala sesuatu secepat dia memikirkannya. Motonya adalah untuk tetap sederhana di dunia yang rumit, tetapi dia tanpa ragu adalah pria atau wanita yang dapat menyimpan dendam.Jung Yi Hyun adalah seorang detektif kejahatan kekerasan dan wanita itu memimpin mantan teman sekelas Yoon Sae Bom yang berlebihan, sahabat, dan suami pura-pura. Di sekolah tinggi, ia membawa tim bisbolnya menuju kemenangan di liga bisbol sekolah tinggi dan terpilih dalam putaran ke-2 draft bisbol liga utama. Namun, ia harus berhenti bermain baseball karena cedera lutut, dan simpati serta keberanian Yoon Sae Bom yang membantunya bangkit kembali.Han Tae Seok menjadi agen statistik sekaligus bertugas di angkatan laut, dan setelah diberhentikan, ia bekerja sebagai pemerintah di sebuah organisasi farmasi. Dia adalah orang yang tepat untuk fungsi yang menangani penyakit menular.',
                'show_date' => 'Nov 5, 2021 - Dec 11, 2021',
                'duration' => '60 min.',
                'director' => 'Ahn Gil Ho',
                'artist' => 'Baek Hyun Jin, Han Hyo Joo, Jo Woo Jin, Lee Ji Ha, Park Hyung Shik, Park Joo Hee',
                'episode' => 12,
                'slug' => 'happiness',
                'image' => 'https://i.mydramalist.com/BWXjV_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Vincenzo',
                'description' => 'Pada usia 8 tahun, Park Ju Hyeong pergi ke Italia setelah dia diterima. Dia saat ini sudah dewasa dan menggunakan nama Vincenzo Casano. Dia adalah seorang penasihat hukum, yang bekerja untuk Mafia sebagai seorang consigliere.Mengingat pertempuran antara pertemuan mafia, dia melarikan diri ke Korea Selatan. Di Korea Selatan, dia bekerja dengan Pengacara Hong Cha Young. Dia adalah tipe pengacara yang akan berhasil memenangkan kasus. Vincenzo Casano mulai menatapnya dengan mata berbintang. Dia juga mencapai kesetaraan sosial dengan caranya sendiri. Jang Jun Woo adalah asisten tahun pertama yang cerdik dan gigih di kantor hukum. Dia berasal dari keluarga kelas pekerja dan ramah dan jujur. Terlepas dari pesonanya yang polos dan penampilannya yang luar biasa, Jun Woo agak aneh dan jujur dan sering melakukan kesalahan dalam pekerjaannya yang membuatnya kesulitan.',
                'show_date' => 'Feb 20, 2021 - May 2, 2021',
                'duration' => '1 hr. 25 min.',
                'director' => 'Kim Hee Won',
                'artist' => 'Jeon Yeo Bin, Jo Han Chul, Kim Yeo Jin, Kwak Dong Yeon, Ok Taec Yeon, Song Joong Ki',
                'episode' => 20,
                'slug' => 'vincenzo',
                'image' => 'https://i.mydramalist.com/vAnBe_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Move To Heaven',
                'description' => 'Geu Roo adalah seorang pria muda dengan sindrom Asperger. Dia bekerja untuk bisnis ayahnya “Move To Heaven.” Tugas mereka adalah mengatur gadget yang ditinggalkan melalui manusia yang sudah meninggal. Suatu hari, ayah Geu Roo sendiri meninggal. Gue Roo ditinggal sendirian, tapi pamannya Sang Koo tiba-tiba muncul di hadapannya. Sang Koo adalah pria yang dingin. Dia menjadi seniman bela diri yang bertarung di bawah tanah. Dia masuk penjara karena apa yang menimpa pertempurannya. Sang Koo sekarang berubah menjadi ayah atau ibu Geu Roo. Mereka menjalankan “Move To Heaven” bersama-sama.',
                'show_date' => 'Mei 14, 2021',
                'duration' => '60 min.',
                'director' => 'Kim Sung Ho',
                'artist' => 'Hong Seung Hee, Ji Jin Hee, Jung Ae Yun, Lee Je Hoon, Shin Soo Oh, Tang Jun Sang',
                'episode' => 10,
                'slug' => 'move-to-heaven',
                'image' => 'https://i.mydramalist.com/Rle36_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Taxi Driver',
                'description' => ' Kisah seorang layanan taksi misterius yang melakukan balas dendam atas nama korban yang tidak bisa mendapatkan keadilan dari hukum. Kim Do Ki adalah pengemudi misterius di perusahaan taksi yang ibunya dibunuh. Kang Ha Na adalah pengacara yang bersemangat. Go Eun adalah spesialis IT, sementara yang lain menganggapnya sebagai peretas. Bersama Kim Do Ki, dia bekerja sebagai bagian dari Perusahaan Taksi Pelangi untuk menyelesaikan masalah orang.',
                'show_date' => 'Apr 9, 2021 - May 29, 2021',
                'duration' => ' 1 hr. 5 min.',
                'director' => 'Park Joon Woo',
                'artist' => 'Cha Ji Yeon, Esom, Kim Eui Sung, Lee Je Hoon, Lee Yoo Joon, Pyo Ye Jin',
                'episode' => 16,
                'slug' => 'taxi-driver',
                'image' => 'https://i.mydramalist.com/2Bkww_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Beyond Evil',
            'description' => 'Lee Dong-Sik ( Shin Ha-Kyun ) pernah menjadi detektif yang cakap. Dia sekarang bekerja di Pos Polisi Manyang di kota kecil dan melakukan semua pekerjaan yang membosankan di stasiun. Hidupnya tenang di sana. Suatu hari, Detektif Han Joo-Won ( Yeo Jin-Goo ) dipindahkan ke pos polisi yang sama. Dia ditugaskan untuk bekerja sebagai bos Lee Dong-Sik dan juga rekannya ',
                'show_date' => 'Feb 19, 2021 - Apr 10, 2021',
                'duration' => ' 1 hr. 5 min.',
                'director' => 'Sim Na-Yeon',
                'artist' => 'Choi Dae-Hoon, Choi Sung Eun, Kim Shin-Rok, Shin Ha-Kyun, Yeo Jin Goo',
                'episode' => 16,
                'slug' => 'beyond-evil',
                'image' => 'https://i.mydramalist.com/0l4wY_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'My Name',
            'description' => 'Ayah Yoon Ji-Woo (Han So-Hee) meninggal tiba-tiba. Dia ingin mati-matian membalas dendam pada siapa pun yang bertanggung jawab atas kematian ayahnya. Yoon Ji-Woo bekerja untuk kelompok kejahatan narkoba Dongcheonpa. Choi Moo-Jin (Park Hee-Soon) adalah bos dari geng narkoba. Dengan bantuan Choi Moo-Jin dan untuk mengungkap alasan kematian ayahnya, Yoon Ji-Woo bergabung dengan departemen kepolisian dan menjadi mata-mata untuk kelompok narkoba. Yoon Ji-Woo ditugaskan untuk bekerja di unit investigasi narkoba di departemen kepolisian. Rekannya di sana adalah Detektif Jeon Pil-Do (Ahn Bo-Hyun)',
                'show_date' => 'Okt 15, 2021',
                'duration' => '50 min',
                'director' => 'Kim Jin Min',
                'artist' => 'Ahn Bo Hyun, Han So Hee, Jang Yool, Kim Sang Ho, Lee Hak Joo, Park Hee Soon',
                'episode' => 8,
                'slug' => 'my-name',
                'image' => 'https://i.mydramalist.com/jD3br_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Law School',
                'description' => 'Seorang profesor di sekolah hukum bergengsi dan murid-muridnya terlibat dalam kasus yang belum pernah terjadi sebelumnya.',
                'show_date' => 'Apr 14, 2021 - Jun 3, 2021',
                'duration' => '1 hr 5 min',
                'director' => 'Kim Seok Yoon',
                'artist' => 'Kim Bum, Kim Myung Min, Lee David, Lee Jung Eun, Lee Soo Kyung, Ryu Hye Young',
                'episode' => 16,
                'slug' => 'law-school',
                'image' => 'https://i.mydramalist.com/jd5jw_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Squid Game',
            'description' => 'Seong Gi-Hun (Lee Jung-Jae) dipecat dari pekerjaannya. Hidupnya sengsara. Seong Gi-Hun mendengar tentang permainan bertahan hidup rahasia, dengan hadiah 45,6 miliar won untuk pemenangnya. Dia memutuskan untuk mengambil bagian dalam permainan. Sementara itu, Cho Sang-Woo (Park Hae-Soo) seperti saudara bagi Seong Gi-Hun dan sebaliknya. Mereka tumbuh di lingkungan yang sama. Terlepas dari latar belakang keluarganya yang miskin, Cho Sang-Woo lulus dari universitas bergengsi dan menemukan pekerjaan yang bagus. Dia sekarang menghadapi krisis, karena penyelewengan dana perusahaan. Dia memutuskan untuk mengambil bagian dalam permainan bertahan hidup rahasia dengan Seong Gi-Hun.',
                'show_date' => ' Sep 17, 2021',
                'duration' => '60 min.',
                'director' => 'Hwang Dong Hyuk',
                'artist' => 'Heo Sung Tae, Jung Ho Yeon, Lee Jung Jae, Park Hae Soo, Wi Ha Joon',
                'episode' => 9,
                'slug' => 'squid-game',
                'image' => 'https://i.mydramalist.com/X6vkX_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Business Proposal',
            'description' => 'romansa kantor antara CEO dan stafnya. Shin Ha Ri adalah seorang pekerja kantoran yang naksir temannya. Namun, itu adalah cinta tak berbalas karena dia sudah punya pacar. Ha Ri memiliki sahabat kaya, Jin Young Seo. Suatu hari, Ha Ri berpura-pura menjadi Young Seo dalam kencan buta. Tanpa diduga, kencan butanya adalah Kang Tae Mu, CEO di perusahaan Ha Ri. Kang Tae Mu adalah CEO gila kerja yang berasal dari keluarga chaebol (kaya). Dia kewalahan oleh kakeknya yang menetapkan beberapa kencan buta untuknya. Akhirnya, Tae Mu memutuskan untuk menikah dengan kencan buta berikutnya.',
                'show_date' => 'Feb 28, 2022 - Apr 5, 2022',
                'duration' => '60 min.',
                'director' => 'Park Seon Ho',
                'artist' => 'Ahn Hyo Seop, Choi Byung Chan, Kim Min Gue, Kim Se Jeong, Lee Deok Hwa, Seol In Ah',
                'episode' => 12,
                'slug' => 'business-proposal',
                'image' => 'https://i.mydramalist.com/v24Pg_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Thirty Nine',
                'description' => 'Trio sahabat berdiri bersama saat mereka mengalami hidup, cinta, dan kehilangan di ambang usia 40 tahun. Cha Mi Jo adalah kepala dokter kulit di sebuah klinik di Gangnam. Dia adalah karakter hangat yang tumbuh di lingkungan yang kaya dengan keluarga yang peduli dan semua yang dia inginkan. Jung Chan Young bermimpi menjadi seorang aktris tetapi malah menjadi guru akting. Meskipun caranya berbicara mungkin tampak blak-blakan dan kasar, ketulusan dalam kata-katanya membuatnya menjadi karakter yang mustahil untuk dibenci. Jang Joo Hee adalah manajer kosmetik department store. Karena kepribadiannya yang pemalu, dia belum benar-benar mengalami hubungan romantis.',
                'show_date' => 'Feb 16, 2022 - Mar 31, 2022',
                'duration' => '1 hr. 18 min.',
                'director' => 'Kim Sang Ho',
                'artist' => 'Jeon Mi Do, Kim Ji Hyun, Lee Moo Saeng, Lee Tae Hwan, Son Ye Jin, Yeon Woo Jin',
                'episode' => 12,
                'slug' => 'thirty-nine',
                'image' => 'https://i.mydramalist.com/v2bEX_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Twenty one Twenty Five',
                'description' => 'Kisah berlatar tahun 1998 dan menceritakan kisah para pemuda yang menemukan arah dan pertumbuhan baru setelah impian mereka direnggut. Dua orang pertama kali bertemu ketika mereka berusia 22 dan 18 tahun dan jatuh cinta bertahun-tahun',
                'show_date' => 'Feb 12, 2022 - Apr 3, 2022',
                'duration' => '1 hr. 15 min.',
                'director' => 'Jung Ji Hyun',
                'artist' => 'Bona, Choi Hyun Wook, Kim Tae Ri, Kim Young Sun, Lee Joo Myung, Nam Joo Hyuk',
                'episode' => 16,
                'slug' => 'twenty-one-twenty-five',
                'image' => 'https://i.mydramalist.com/ROOPo_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Forecasting Love and Weather',
                'description' => 'Sebuah kisah yang menggambarkan cinta dan kehidupan kerja karyawan di Administrasi Meteorologi Korea. Jin Ha-Kyung dan Lee Shi-Woo adalah dua orang yang bekerja di sana.',
                'show_date' => 'Feb 12, 2022 - Apr 3, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Cha Young Hoon',
                'artist' => 'Jung Woon Sun, Kim Mi Kyung, Park Min Young, Song Kang, Yoon Park, Yura',
                'episode' => 16,
                'slug' => 'forecasting-love-and-weather',
                'image' => 'https://i.mydramalist.com/11XPQ_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'All of Us Are Dead ',
                'description' => 'Sekelompok siswa sekolah menengah terjebak di Sekolah Menengah Hyosan selama wabah virus zombie. Para siswa mati-matian berusaha menghindari menjadi zombie dan melarikan diri dari sekolah mereka.',
                'show_date' => 'Jan 28,2022',
                'duration' => '1 hr. 2 min.',
                'director' => 'Lee Jae Gyoo',
                'artist' => 'Jo Yi Hyun, Kim Byung Chul, Park Ji Hoo, Park Solomon, Yoo In Soo, Yoon Chan Young',
                'episode' => 12,
                'slug' => 'all-of-us-are-dead',
                'image' => 'https://i.mydramalist.com/WRQmX_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Ghost Doctor',
                'description' => 'Cha Young Min adalah seorang dokter jenius, dengan keterampilan unggul dalam operasi, tapi dia arogan dan egois. Suatu hari, dia terlibat dalam kasus yang tidak terduga, dan karena itu, rohnya merasuki tubuh dokter lain, yaitu Seong Tak. Kedua dokter ini sangat bertolak belakang, dengan kepribadian dan kemampuan medis yang berlawanan.Sementara Young Min arogan dan berdarah dingin, yang hanya peduli dengan karirnya, dan tidak peduli dengan cerita pribadi pasiennya, Seong Tak adalah dokter residen paling beruntung dan terkaya yang kakeknya adalah pendiri rumah sakit Myung-shin dan ibu adalah ketua rumah sakit. Tidak pernah ingin menjadi dokter yang baik, ia diproses oleh dua dokter hantu dengan latar belakang yang sama sekali berbeda.',
                'show_date' => 'Jan 3, 2022 - Feb 22, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Boo Sung Chul',
                'artist' => 'Kim Bum, Kim Jae Yong, Rain, Seo Ji Young, Son Na Eun, Uee',
                'episode' => 16,
                'slug' => 'ghost-doctor',
                'image' => 'https://i.mydramalist.com/peyDr_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'The Silent Sea',
            'description' => 'Ditetapkan di masa depan, ketika planet ini menderita kekurangan air dan makanan yang disebabkan oleh penggurunan. Yoon-Jae (Gong Yoo) adalah seorang tentara untuk badan antariksa. Dia dipilih untuk sebuah tim, termasuk Ji-An (Bae Doo-Na), untuk melakukan perjalanan ke bulan. Misi mereka adalah untuk mengambil sampel misterius dari stasiun penelitian yang ditinggalkan.',
                'show_date' => 'Dec 24,2022',
                'duration' => '50 min.',
                'director' => 'Choi Hang Yong',
                'artist' => 'Bae Doo Na, Gong Yoo, Heo Sung Tae, Jung Soon Won, Lee Joon, Lee Moo Saeng',
                'episode' => 8,
                'slug' => 'the-silent-sea',
                'image' => 'https://i.mydramalist.com/wLdVN_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Bulgasal',
                'description' => 'drama sejarah fantasi yang menampilkan makhluk mitos abadi, Bulgasal. Dan Hwal adalah manusia abadi yang telah hidup selama sekitar 600 tahun. Dia adalah perwira militer Dinasti Joseon yang bertugas untuk membunuh sisa-sisa dinasti sebelumnya. Di masa lalu, dia memiliki seorang istri, Dan Sol, putri jenderal yang berkuasa saat itu. Sementara itu, Min Sang Woon dulunya abadi tetapi dia bereinkarnasi menjadi manusia dan saat ini hidup sebagai wanita biasa. Manusia abadi lainnya adalah Ok Eul Tae yang menikmati keabadian dan kekuatannya.',
                'show_date' => 'Dec 18, 2021 - Feb 6, 2022',
                'duration' => '1 hr. 15 min.',
                'director' => 'Jang Young Woo',
                'artist' => 'Gong Seung Yeon, Jung Jin Young, Kwon Na Ra, Lee Jin Wook, Lee Joon, Park Myung Shin',
                'episode' => 16,
                'slug' => 'bulgasal',
                'image' => 'https://i.mydramalist.com/W4krO_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Snowdrop',
            'description' => 'Kisah cinta dengan latar belakang pemberontakan politik di Korea Selatan. Im Soo Ho (Jung Hae In) adalah seorang mahasiswa di sebuah perguruan tinggi terkemuka. Dia adalah orang Korea yang juga memiliki kewarganegaraan Jerman. Di sisi lain, Eun Young Ro (Jisoo) jurusan Sastra Inggris di universitas wanita. Sooho dan Young Ro bertemu di kencan buta. Young Ro langsung jatuh cinta pada pesona dan karisma misterius Soo Ho. Selama Gerakan Demokratik Korea pada tahun 1987, Sooho yang terluka parah ditemukan oleh Young Ro di asramanya. Perasaan di antara keduanya tumbuh saat mereka menghabiskan waktu bersama.',
                'show_date' => 'Dec 18, 2021 - Feb 6, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Jo Hyun Taek',
                'artist' => 'Jang Seung Jo, Jung Hae In, Kim Hye Yoon, Kim Ji Soo, Yoo In Na, Yoon Se Ah',
                'episode' => 16,
                'slug' => 'snowdrop',
                'image' => 'https://i.mydramalist.com/RKBWE_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Bad and Crazy',
            'description' => 'Soo-Yeol (Lee Dong-Wook) bekerja sebagai petugas polisi untuk Departemen Kepolisian Mooui. Dia kompeten dalam pekerjaannya, tetapi dia juga memiliki etika yang dipertanyakan. Dia akan melakukan apa saja untuk mencapai kesuksesan. Karena kepribadiannya yang ambisius, ia telah menerima promosi dalam waktu singkat. Kehidupannya yang mulus tiba-tiba berubah dengan munculnya K (Wi Ha-Joon). K adalah orang yang benar, tetapi juga orang yang gila. Setiap kali dia menghadapi ketidakadilan, dia menghadapinya dengan kepalan tangan. Dia bermimpi menjadi pahlawan',
                'show_date' => 'Dec 17, 2021 - Jan 28, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Yoo Seon Dong',
                'artist' => 'Cha Shi Won, Han Ji Eun, Lee Dong Wook, N, Sung Ji Ru, Wi Ha Joon',
                'episode' => 12,
                'slug' => 'bad-and-crazy',
                'image' => 'https://i.mydramalist.com/RVbJz_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'One Ordinary Day',
            'description' => 'Kim Hyun Soo (Kim Soo Hyun), seorang mahasiswa biasa yang hidupnya mencapai titik terendah setelah dia dituduh melakukan pembunuhan. Untuk bertahan hidup dalam sistem hukum yang kejam, dia mengerahkan segalanya untuk membuktikan bahwa dia tidak bersalah. Kim Hyun Soo menerima bantuan dari Shin Joong Han (Cha Seung Won), seorang pengacara biasa-biasa saja yang nyaris tidak memenangkan kasus apapun. Meskipun memiliki reputasi buruk sebagai pengacara, Shin Joong Han adalah satu-satunya pengacara yang menjangkau Kim Hyun Soo.',
                'show_date' => 'Nov 27, 2021 - Dec 19, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Lee Myung Woo',
                'artist' => 'Cha Seung Won, Kim Hong Pa, Kim Shin Rok, Kim Soo Hyun, Lee Seol, Yang Kyung Won',
                'episode' => 8,
                'slug' => 'one-ordinary-day',
                'image' => 'https://i.mydramalist.com/jP5Vd_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Hellbound',
            'description' => ' makhluk gaib menyeret manusia ke neraka. Jung Jin Soo adalah pemimpin sekte karismatik namun misterius bernama Saejinrihwe. Dia menceritakan kedatangan malaikat maut dari fenomena neraka kepada orang-orang yang beriman. Bae Young Jae adalah PD stasiun penyiaran yang bertujuan untuk mengungkapkan kebenaran tentang kelompok pemujaan Saejinrihwe. Istrinya, Song So Hyun, sedang berjuang dalam rasa sakit emosional. Sementara itu, Min Hye Jin adalah pengacara terhadap kelompok Hwasalchok (pengikut Saejinrihwe). Jin Kyung Hoon adalah seorang detektif yang menyelidiki kasus terkait fenomena malaikat maut.',
                'show_date' => 'Nov 19,2021',
                'duration' => '50 min',
                'director' => 'Yeon Sang Ho',
                'artist' => 'Kim Do Yoon, Kim Hyun Joo, Park Jung Min, Won Jin Ah, Yang Ik Jun, Yoo Ah In',
                'episode' => 6,
                'slug' => 'hellbound',
                'image' => 'https://i.mydramalist.com/6weyW_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Now We Are Breaking Up',
            'description' => 'Menceritakan kenyataan pahit dari orang-orang yang putus.Ha Yong Eun (Song Hye Kyo) bekerja sebagai desainer di sebuah perusahaan fashion, dia cerdas, cantik, dan selalu mengutamakan dirinya sendiri. Di sisi lain, Yoon Jae Kook (Jang Ki Yong) adalah seorang fotografer fashion yang tampan dan pintar. Keduanya ingin menyampaikan pesan bahwa putus mungkin bukan akhir, bisa jadi pelengkap cinta dan kehidupan kita.',
                'show_date' => 'Nov 12, 2021 - Jan 8, 2022',
                'duration' => '60 min.',
                'director' => 'Lee Gil Bok',
                'artist' => 'Choi Hee Seo, Choi Hong Il, Jang Ki Yong, Kim Joo Heon, Nam Ki Ae, Song Hye Kyo',
                'episode' => 16,
                'slug' => 'now-we-are-breaking-up',
                'image' => 'https://i.mydramalist.com/BKZ4z_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Red Sleeve',
            'description' => 'Kisah cinta antara Lee San kemudian Raja Jeongjo dari Joseon (Lee Junho) dan pelayan istana Seong Deok Im (Lee Se Young). Lee San mengembangkan perasaan untuk Seong Deok Im. Setelah naik takhta, sekarang Raja Jeongjo memintanya untuk menjadi selirnya. Seong Deok Im yang memiliki kebanggaan kuat dalam tugasnya menolak lamaran Raja karena menjadi selir kerajaan akan menyita kebebasannya dan mungkin membawa kesengsaraan alih-alih kebahagiaan.',
                'show_date' => 'Nov 12, 2021 - Jan 1, 2022',
                'duration' => '1 hr. 20 min.',
                'director' => ' Jung Ji In',
                'artist' => 'Jang Hee Jin, Kang Hoon, Kang Mal Geum, Lee Deok Hwa, Lee Jun Ho, Lee Se Young',
                'episode' => 17,
                'slug' => 'red-sleeve',
                'image' => 'https://i.mydramalist.com/2WpKk_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Melancholia',
                'description' => 'Bertempat di sebuah perguruan tinggi non-publik yang korup dengan perlakuan istimewa, “Melancholia” akan menceritakan kisah indah seorang instruktur matematika dan seorang sarjana matematika yang jenius. Ji Yoon Soo adalah seorang guru matematika perguruan tinggi tinggi yang tampaknya benar di alam terbuka tetapi menjadi sangat ulet dan keras kepala segera setelah dia mengambil keputusan tentang sesuatu. Sangat antusias tentang matematika, dia adalah seorang instruktur yang mendorong murid-muridnya untuk menemukan jawaban mereka sendiri. Jenius matematika Baek Seung Yoo adalah pria dengan sedikit frasa yang merupakan orang luar sukarela dan suka memotret dengan kamera DSLR. Meskipun menduduki peringkat terakhir di fakultasnya yang tinggi, dia benar-benar mendominasi Olimpiade matematika saat dia menjadi lebih muda, masuk Institut Teknologi Massachusetts pada usia 10 tahun, dan putus sekolah pada usia 12 tahun.',
                'show_date' => ' Nov 10, 2021 - Dec 30, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Sang Hyub',
                'artist' => 'Byun Jung Soo, Choi Dae Hoon, Im Soo Jung, Jang Hyun Sung, Jin Kyung, Lee Do Hyun',
                'episode' => 16,
                'slug' => 'melancholia',
                'image' => 'https://i.mydramalist.com/WDo4P_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Jirisan',
                'description' => 'Berlawanan dengan latar belakang pemandangan Gunung Jiri yang menjulang, di mana penjaga hutan dan berbagai karyawan Taman Nasional Jirisan mendaki melalui daerah gunung yang misterius dan belum dijelajahi, mencoba menyelamatkan para penyintas dan pejalan kaki yang hilang. Seo Yi Kang adalah penjaga taman tertinggi yang memiliki pengalaman luas dalam navigasi, membuatnya terinformasi dalam hal memantau orang-orang yang salah tempat. Suatu hari, dia menjadi kaki tangan Kang Hyun Jo, seorang penjaga taman pemula yang merupakan lulusan akademi militer dan mantan letnan yang mengalami insiden mengerikan di Gunung Jiri yang membuatnya menjadi seorang penjaga. Drama ini ditargetkan pada misteri seputar lalu lintas gunung yang banyak; orang-orang yang datang untuk membunuh, dan orang-orang yang datang untuk mengakhiri hidup mereka.',
                'show_date' => 'Oct 23, 2021 - Dec 12, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Lee Eung Bok',
                'artist' => 'Jo Han Chul, Joo Ji Hoon, Jun Ji Hyun, Jun Suk Ho, Oh Jung Se, Sung Dong Il',
                'episode' => 16,
                'slug' => 'jirisan',
                'image' => 'https://i.mydramalist.com/EwpK7_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'The King\'s Affection',
            'description' => 'Drama fiksi era Joseon menceritakan kisah Lee Hwi (Park Eun Bin), seorang putra mahkota wanita yang menyamar. Cerita dimulai ketika Putri Mahkota melahirkan anak kembar, yang dianggap sebagai pertanda buruk selama era Joseon. Keluarga kerajaan memutuskan untuk mengeksekusi kembaran perempuan itu, tetapi Putri Mahkota mencoba menyelamatkan putrinya dengan menyembunyikannya dari istana. Sayangnya, kembaran laki-laki Lee Hwi meninggal karena suatu penyakit. Putri Mahkota membawa kembali putrinya dan membesarkannya sebagai anak laki-laki menggantikan Lee Hwi, Putra Mahkota. Hal-hal mulai berantakan setelah Lee Hwi jatuh cinta dengan tutornya, Jung Ji Woon (Rowoon).',
                'show_date' => 'Oct 11, 2021 - Dec 14, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Song Hyun Wook',
                'artist' => 'Bae Yoon Kyung, Choi Byung Chan, Jung Chae Yeon, Nam Yoon Su, Park Eun Bin, Rowoon',
                'episode' => 20,
                'slug' => 'the-kings-affection',
                'image' => 'https://i.mydramalist.com/XVVjx_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'The Veil',
            'description' => 'Han Ji-Hyuk (Namkoong Min) adalah agen terbaik di National Intelligence Service (NIS). Dia dikagumi oleh rekan-rekannya, tetapi dia menempatkan NIS dalam krisis. Dia kemudian menghilang.',
                'show_date' => ' Sep 17, 2021 - Oct 23, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Sung Yong',
                'artist' => ' Jang Young Nam, Kim Do Hyun, Kim Ji Eun, Kim Jong Tae, Namgoong Min, Park Ha Sun',
                'episode' => 12,
                'slug' => 'the-veil',
                'image' => 'https://i.mydramalist.com/Xkn8n_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Yumi\'s Cell',
            'description' => 'Yu-Mi (Kim Go-Eun) adalah seorang wanita pekerja lajang biasa. Dia tidak pandai mengungkapkan perasaannya. Melalui hubungan romantis dan pekerjaannya, ia tumbuh sebagai pribadi dan menemukan kebahagiaan dalam kehidupan sehari-harinya. Yu-Mi memiliki sel-sel di otaknya yang mewakili berbagai emosi seperti cinta, kekerasan, rasionalitas, baik, dan buruk. Sel-sel kecil di otaknya ini bekerja secara aktif untuknya. Mereka menangani emosi dan masalahnya.',
                'show_date' => 'Sep 17, 2021 - Oct 30, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Lee Sang Yeob',
                'artist' => 'Ahn Bo Hyun, Jung Soon Won, Kim Go Eun, Lee Yoo Bi, Park Ji Hyun, Park Jin Young',
                'episode' => 14,
                'slug' => 'yumis-cell',
                'image' => 'https://i.mydramalist.com/4JzlJ_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Hometown Cha-Cha-Cha',
                'description' => 'Yoon Hye Jin adalah seorang wanita yang memiliki kecantikan dan otak masing-masing. Rencana gaya hidupnya berantakan karena sedikit kebenaran di hatinya, dan setelah berbagai hambatan, dia bertindak ke desa tepi laut Gongjin dan bertemu Tuan Hong.Hong Doo Shik, yang disebut sebagai Mr. Hong round metropolis. Dia menganggur secara formal, tetapi dia memahami pekerjaan aneh yang tampaknya membantu setiap orang di Gongjin dengan keadaan apa pun yang mereka hadapi.',
                'show_date' => 'Aug 28, 2021 - Oct 17, 2021',
                'duration' => '1 hr. 20 min.',
                'director' => 'Yoo Je Won',
                'artist' => 'In Gyo Jin, Jo Han Chul, Kim Seon Ho, Lee Bong Ryun, Lee Sang Yi, Shin Min Ah',
                'episode' => 16,
                'slug' => 'hometown-cha-cha-cha',
                'image' => 'https://i.mydramalist.com/ZeKv1_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'D.P.',
                'description' => 'Prajurit swasta Jun Ho adalah seorang pemuda bingung yang bertugas di militer secara normal seperti orang Korea lainnya. Suatu hari, dia tiba-tiba menjadi anggota tim penangkapan pembelot militer. Karena itu, dia ditugaskan untuk menangkap desertir dan harus bergulat dengan kasus-kasus yang lebih meresahkan mengapa beberapa tentara merasa mereka tidak punya pilihan lain selain pergi tanpa izin resmi.',
                'show_date' => 'Agustus 27,2021',
                'duration' => '50 min.',
                'director' => 'Han Jun Hee',
                'artist' => 'Hong Kyung, Jung Hae In, Kim Sung Kyun, Koo Kyo Hwan, Lee Jun Young, Son Seok Koo',
                'episode' => 6,
                'slug' => 'dp',
                'image' => 'https://i.mydramalist.com/XkYln_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Blue Birthday',
                'description' => 'Sebuah drama fantasi romantis di mana Oh Ha Rin akan mengunjungi kembali masa lalu melalui foto misterius yang ditinggalkan oleh cinta pertamanya, Ji Seo Jun yang meninggal pada hari ulang tahunnya 10 tahun yang lalu. Dia telah memutuskan untuk mengaku kepada teman masa kecilnya sejak sekolah dasar tetapi dia akhirnya mengambil nyawanya sendiri, sangat mengejutkan dan ngeri. Dia akan mengaku padanya ketika dia bertemu kematiannya yang tiba-tiba di ruang fotografi. Dia saat ini bekerja di tempat penampungan hewan peliharaan yang ditinggalkan, tetapi pada peringatan 10 tahun kejadian itu, dia memiliki beberapa foto yang ditinggalkan oleh cinta pertamanya. Ha Rin, yang kenangan menyakitkannya dihidupkan kembali, memutuskan untuk membakar semua gambar itu. Ketika dia membakar foto-foto itu, dia tiba-tiba menyadari bahwa dia kembali ke hari dia mengambil foto itu 10 tahun yang lalu. Kamera hanya memiliki 8 gambar, jadi Ha Rin hanya memiliki 8 kesempatan untuk kembali ke masa lalu',
                'show_date' => 'Jul 23, 2021 - Sep 11, 2021',
                'duration' => '20 min.',
                'director' => 'Park Dhan Hee',
                'artist' => 'Kim Gyeol Yu, Kim Yi Seo, Lee Sang Jun, Yang Hong Seok, Yeri',
                'episode' => 16,
                'slug' => 'blue-birthday',
                'image' => 'https://i.mydramalist.com/x1JYw_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'The Witch\'s Diner',
                'description' => 'Kenangan dari orang-orang yang gigih yang datang untuk mengkonsumsi hidangan ajaib dengan harapan keinginan non-publik mereka dikabulkan, bahkan dengan harga yang harus dibayar dalam jiwa mereka sendiri. Jo Hee Ra telah kehilangan hitungan tahun yang dia habiskan untuk hidup. Dia memiliki perasaan, meskipun, bahwa dia telah menjadi lebih tua dari manusia yang dikenal dalam sejarah. Dia memilih untuk berubah menjadi penyihir setelah mengalami nasib yang menyedihkan di tahun 1920-an dan sekarang berjalan bersama di sebuah restoran misterius dengan seorang gadis bernama Jin.',
                'show_date' => 'Jul 16, 2021 - Aug 13, 2021',
                'duration' => '44 min.',
                'director' => 'So Jae Hyun',
                'artist' => 'Chae Jong Hyeop, Ha Do Gwon, Nam Ji Hyun, Son Kwang Eop, Song Ji Hyo, Yoon Da Young',
                'episode' => 8,
                'slug' => 'the-witchs-diner',
                'image' => 'https://i.mydramalist.com/w6wqn_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'The Devil Judge',
                'description' => 'Ditetapkan dalam versi dystopian Korea masa kini di mana kehidupan sehari-hari adalah salah satu kekacauan dan masyarakat telah runtuh sampai-sampai orang secara terbuka menyuarakan ketidakpercayaan dan kebencian mereka kepada para pemimpin mereka. Di dunia yang kehilangan hukum dan ketertiban ini, Hakim Ketua Pengadilan Kang mengisyaratkan perlunya perubahan. Ruang sidangnya adalah subjek dari reality show di mana dia tanpa ampun menghukum yang bersalah, membuatnya mendapat julukan "Hakim Iblis". Sebagai sosok pemecah belah dengan aura misteri yang memungkiri identitas dan ambisinya yang sebenarnya, publik tidak yakin apakah dia pahlawan sejati atau seseorang, dengan sengaja menabur benih ketidakpuasan di ruang sidangnya. Persaingan sengit telah terbentuk antara "Hakim Iblis" dan Jung Sun Ah yang sangat ambisius, yang telah bangkit dari kemiskinan untuk menjadi direktur yayasan tanggung jawab sosial perusahaan. Ke dunia yang bergejolak ini, masuklah dua teman masa kecil dalam pencarian keadilan sejati: Hakim pemula Kim Ga On dan Petugas Polisi Yoon Soo Hyun.',
                'show_date' => ' Jul 3, 2021 - Aug 22, 2021',
                'duration' => '1 hr. 15 min.',
                'director' => 'Choi Jung Gyu',
                'artist' => 'Ahn Nae Sang, Ji Sung, Kim Jae Kyung, Kim Min Jung, Park Gyu Young, Park Jin Young',
                'episode' => 16,
                'slug' => 'the-devil-judge',
                'image' => 'https://i.mydramalist.com/XJL7Z_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Nevertheless',
            'description' => ' Park Jae-Eon (Song Kang) adalah seorang mahasiswa, jurusan seni. Dia tampak baik untuk semua orang dan dia biasanya ceria. Namun, dia benar-benar acuh tak acuh terhadap orang lain dan dia tidak ingin memiliki hubungan romantis. Tanpa diduga, dia jatuh cinta pada Yoo Na-Bi (Han So-Hee) dan mulai berubah. Yoo Na-Bi adalah mahasiswa seni di universitas yang sama dengan Park Jae-Eon. Di masa lalunya, dia putus dengan cinta pertamanya karena cara yang tidak setia. Setelah itu, memutuskan untuk tidak goyah oleh cinta. Dia kemudian bertemu Park Jae-Eon dan mengembangkan perasaan untuknya.',
                'show_date' => 'Jun 19, 2021 - Aug 21, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Ga Ram',
                'artist' => ' Chae Jong Hyeop, Han Eu Ddeum, Han So Hee, Kim Min Gwi, Song Kang, Yang Hye Ji',
                'episode' => 10,
                'slug' => 'nevertheless',
                'image' => 'https://i.mydramalist.com/w6jkA_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Hospital Playlist 2',
                'description' => 'Setiap hari adalah hari yang luar biasa bagi lima dokter dan pasien mereka di dalam rumah sakit, tempat kelahiran, kematian, dan segala sesuatu di antaranya hidup berdampingan.',
                'show_date' => 'Jun 17, 2021 - Sep 16, 2021',
                'duration' => ' 1 hr. 40 min.',
                'director' => 'Shin Won Ho',
                'artist' => 'Jeon Mi Do, Jo Jung Suk, Jung Kyung Ho, Kim Dae Myung, Shin Hyun Bin, Yoo Yeon Seok',
                'episode' => 12,
                'slug' => 'hospital-playlist-2',
                'image' => 'https://i.mydramalist.com/dKY0d_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Racket Boys',
                'description' => 'Berkisah tentang klub bulu tangkis sekolah pusat ragtag yang mengajukan tawaran untuk gelar remaja. Ini digambarkan sebagai dramatisasi yang jujur dan menginspirasi yang akan menunjukkan perkembangan remaja yang relatable. Ra Young Ja adalah pemain bulu tangkis yang luar biasa. Dia saat ini membimbing kru bulu tangkis sekolah pusat. Dia memiliki daya tarik sebagai mentor. Awak bulu tangkis terdiri dari remaja putra dan putri berusia 16 tahun, namun mereka tidak prima. Kelompok berkembang saat mereka berpartisipasi dalam persaingan atletik yang lebih rendah.',
                'show_date' => 'May 31, 2021 - Aug 9, 2021',
                'duration' => '1 hr. 15 min.',
                'director' => 'Jo Young Kwang',
                'artist' => ' Choi Hyun Wook, Kim Kang Hoon, Kim Sang Kyung, Oh Na Ra, Son Sang Yeon, Tang Jun Sang',
                'episode' => 16,
                'slug' => 'racket-boys',
                'image' => 'https://i.mydramalist.com/QARr2_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'My Roommate Is a Gumiho',
                'description' => 'Shin Woo Yeo adalah seorang profesor yang tampan dan cerdas. Dia juga rubah berekor sembilan berusia 999 tahun. Untuk menjadi manusia, dia mengumpulkan energi manusia dalam manik-manik. Segera, dia akan menjadi manusia.',
                'show_date' => 'May 26, 2021 - Jul 15, 2021',
                'duration' => ' 1 hr. 10 min.',
                'director' => 'Nam Sung Woo, Park Joon Hwa',
                'artist' => 'Bae In Hyuk, Jang Ki Yong, Kang Han Na, Kim Do Wan, Lee Hye Ri, Park Kyung Hye',
                'episode' => 16,
                'slug' => 'my-roommate-is-a-gumiho',
                'image' => 'https://i.mydramalist.com/xJdOy_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Mad for Each Other',
                'description' => 'Tentang dua manusia dengan kisah menyakitkan pribadi mereka yang melalui cara rumit yang melukai dan memulihkan bahkan saat jatuh cinta satu sama lain. No Hwi Oh adalah seorang detektif di divisi kejahatan kekerasan Kantor Polisi Gangnam. Dia berpikir bahwa dia baik-baik saja sampai gaya hidupnya tiba-tiba berubah dan dia berubah menjadi orang “gila” yang tidak bisa menahan amarahnya tentang apapun. Lee Min Kyung adalah seorang gadis yang terjebak dalam delusi dan kompulsi sendiri. Dia telah menjalani kehidupan sehari-hari sebagai wanita yang tenang dengan proses yang layak sampai “kejadian itu” yang menyebabkan seluruh kehidupannya terputus. Akibatnya, dia berubah menjadi tidak bisa mempercayai setiap orang dan terjebak dalam penjara buatannya sendiri. Khayalannya juga memiliki efek samping yang tidak menguntungkan yang membuat semua orang di sekitarnya merasa kesal.',
                'show_date' => 'May 24, 2021 - Jun 21, 2021',
                'duration' => '35 min.',
                'director' => 'Lee Tae Gon',
                'artist' => 'Ahn Woo Yeon, Baek Ji Won, Jung Woo, Kim Nam Hee, Lee Soo Hyun, Oh Yeon Seo',
                'episode' => 13,
                'slug' => 'mad-for-each-other',
                'image' => 'https://i.mydramalist.com/xJ7pr_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Doom at Your Service ',
            'description' => 'Dong-Kyeong (Park Bo-Young) adalah editor untuk perusahaan novel web. Myeol-Mang (Seo In-Guk), tiba-tiba muncul dalam kehidupannya yang biasa. Dia membuat kontrak 100 hari dengan Myeol-Mang, mempertaruhkan nyawa dan cintanya.',
                'show_date' => 'May 10, 2021 - Jun 29, 2021',
                'duration' => '1 hr. 5 min.',
                'director' => 'Kwon Young Il',
                'artist' => 'Dawon, Kang Tae Oh, Lee Soo Hyuk, Park Bo Young, Seo In Guk, Shin Do Hyun',
                'episode' => 16,
                'slug' => 'doom-at-your-service',
                'image' => 'https://i.mydramalist.com/vlNOX_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Imitation',
            'description' => 'Ma-Ha (Jung Ji-So) adalah anggota girl grup Teaparty. Anggota lainnya adalah Ri-A (Minseo) dan Hyun-Ji (Lim Na-Young). Sejak debut mereka, mereka belum banyak meraih sukses. Ma-Ha telah menerima perhatian karena kemiripannya dengan penyanyi populer Ri-Ma (Park Ji-Yeon).',
                'show_date' => 'May 7, 2021 - Jul 23, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Han Hyun Hee',
                'artist' => 'Chani, Im Na Young, Jeong Ji So, Jeong Yun Ho, Lee Jun Young, Park Ji Yeon',
                'episode' => 12,
                'slug' => 'imitation',
                'image' => 'https://i.mydramalist.com/WwbnX_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Youth of May',
            'description' => 'Pada bulan Mei 1980, selama masa pergolakan Pemberontakan Gwangju, Hee-Tae (Lee Do-Hyun) dan Myung-Hee (Go Min-Si) jatuh cinta. Cinta mereka sepertinya ditakdirkan oleh takdir.',
                'show_date' => 'May 3, 2021 - Jun 8, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Song Min Yeop',
                'artist' => 'Geum Sae Rok, Go Min Si, Lee Do Hyun, Lee Sang Yi, Oh Man Suk, Uhm Hyo Sub',
                'episode' => 12,
                'slug' => 'youth-of-may',
                'image' => 'https://i.mydramalist.com/dNO1d_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'So I Married an Anti-Fan',
                'description' => 'Hoo Joon adalah bintang top sedangkan Geun Young adalah reporter majalah. Untuk artikel berita potensial, Geun Young memutuskan untuk menghadiri upacara pembukaan klub. Di sana, dia menyaksikan perilaku kekerasan bintang top Hoo Joon dan dia juga muntah padanya secara tidak sengaja. Hal ini menyebabkan Geun Young kehilangan pekerjaannya. Percaya bahwa Hoo Joon berada di belakang pemecatannya, dia memutuskan untuk mendapatkannya kembali dengan berdemonstrasi di depan kantor manajemen Hoo Joons. Perlahan, dia mulai menerima liputan media tentang demonstrasinya dan segera menjadi terkenal sebagai anti-fan. Seorang PD mendekati Geun Young tentang berpartisipasi dalam acara TV realitas yang berkisar pada ide bintang top dan anti-penggemar mereka yang hidup bersama. Karena menganggur, dia memutuskan untuk menerima tawaran itu. Sementara itu, Hoo Joon ditawari acara TV realitas yang sama dan menerima tawaran untuk meningkatkan citranya. Hoo Joon dan Geun Young mencoba saling memberikan waktu yang sulit di reality show, tetapi segera mulai saling jatuh cinta.',
                'show_date' => 'Apr 30, 2021 - Jun 19, 2021',
                'duration' => '1 hr. 2 min.',
                'director' => 'Kang Cheol Woo',
                'artist' => 'Choi Soo Young, Choi Tae Joon, Han Ji An, Hwang Chan Sung, Kim Min Kyu, Kim Sun Hyuk',
                'episode' => 16,
                'slug' => 'so-i-married-an-anti-fan',
                'image' => 'https://i.mydramalist.com/QkmV5_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'Sell Your Haunted House ',
                'description' => 'Pertunjukan misterius tentang pedagang tanah yang mengusir dan memusnahkan bangunan tempat hantu secara berturut-turut dan orang-orang masuk ke dalamnya. Terlepas dari kenyataan bahwa ketua dan pengusir setan Daebak Land, Hong Ji Ah tampak luar biasa dengan keunggulan dan pengetahuannya, dia benar-benar pengusir setan pemarah yang tangannya mengepal sebelum kata-katanya. Kapasitasnya untuk mengusir setan telah diturunkan dari ibunya. Gracious In Bum adalah seorang scalawag yang tidak menaruh stok di hantu tetapi menggunakannya untuk menghasilkan uang. Dia memiliki pengaturan kemampuan yang ideal untuk seorang penipu, memiliki pilihan untuk memanfaatkan persepsi dan kemampuan berpikirnya yang luar biasa untuk memutuskan keadaan dan hasil akhir seperti harapan masa depan untuk keadaan apa pun. Hong Ji Ah akan bekerja dengan Gracious In Bum untuk menyelesaikan misteri di balik kematian ibunya 20 tahun sebelumnya.',
                'show_date' => 'Apr 14, 2021 - Jun 9, 2021',
                'duration' => '1 hr. 10 min.',
                'director' => 'Park Jin Suk',
                'artist' => 'Baek Eun Hye, Choi Woo Seong, Jang Na Ra, Jung Yong Hwa, Kang Hong Suk, Kang Mal Geum',
                'episode' => 16,
                'slug' => 'sell-your-haunted-house',
                'image' => 'https://i.mydramalist.com/v6LQB_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'My Liberation Notes',
                'description' => 'Kisah tiga saudara kandung dan orang asing misterius yang ingin keluar dari kehidupan frustasi mereka. Terletak di Desa Sanpo, tempat di mana biasanya arus masuk manusia yang pergi lebih baik daripada mereka yang pindah. Ada tiga saudara Yeom, Chang Hee, Mi Jung, dan Ki Jung yang semuanya harus keluar dari kehidupan yang tersumbat. dengan ‘tidak ada jawaban’.Suatu hari, seorang pria misterius bernama Pak Goo tiba-tiba bertindak ke lingkungan mereka. Dia pemabuk, merosot, dan sepertinya dia memiliki banyak beban dan rahasia dan teknik. Karakter hati-hati dan pilihannya untuk tetap dalam bisnis pribadinya, membuatnya berkomunikasi dengan kota, bahkan membuat Mi Jung yang pemalu, anak bungsu dari tiga bersaudara, untuk mendekatinya.',
                'show_date' => 'Apr 9, 2022 - May 29, 2022',
                'duration' => '1 hr. 7 min.',
                'director' => 'Kim Seok Yoon',
                'artist' => 'Chun Ho Jin, Kim Ji Won, Lee El, Lee Ki Woo, Lee Min Ki, Son Seok Koo',
                'episode' => 16,
                'slug' => 'my-liberation-notes',
                'image' => 'https://i.mydramalist.com/jd5jw_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-05 14:00:32',
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Our Blues',
                'description' => '‘Our Blues’ adalah drama bergaya omnibus yang berpusat di sekitar hubungan 14 protagonisnya. Dengan latar belakang Pulau Jeju, ia menceritakan 8 kisah berbeda dari orang-orang yang tinggal di pulau itu.',
                'show_date' => 'Apr 9, 2022 - Jun 12, 2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Kyu Tae',
                'artist' => 'Cha Seung Won, Han Ji Min, Lee Byung Hun, Lee Jung Eun, Shin Min Ah, Uhm Jung Hwa',
                'episode' => 20,
                'slug' => 'our-blues',
                'image' => 'https://i.mydramalist.com/48LYQ_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Tomorrow',
            'description' => 'Choi Joon-Woong (Ro Woon) mencari pekerjaan, tetapi sulit baginya untuk dipekerjakan. Kecuali untuk itu, dia tampak seperti pria yang sempurna. Dia lulus dari universitas bergengsi dan dia memiliki orang tua yang kaya. Suatu malam, dia secara tidak sengaja bertemu dengan malaikat maut Gu Ryeon (Kim Hee-Seon) dan Im Ryoog-Gu. Kedua malaikat maut itu tergabung dalam tim manajemen krisis. Gu Ryeon adalah pemimpinnya dan Im Ryoog-Gu adalah anggotanya. Tujuan mereka adalah untuk menyelamatkan orang yang ingin bunuh diri. Segera, Choi Joon-Woong menjadi anggota baru tim manajemen krisis.',
                'show_date' => ' Apr 1, 2022 - May 21, 2022',
                'duration' => '60 min.',
                'director' => 'Kim Tae Yoon',
                'artist' => 'Kim Hae Sook, Kim Hee Sun, Lee Soo Hyuk, Moon Seo Youn, Rowoon, Yoon Ji On',
                'episode' => 16,
                'slug' => 'tomorrow',
                'image' => 'https://i.mydramalist.com/qjBQ2_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Mouse',
            'description' => 'Jung Ba-Reum ( Lee Seung-Gi ) adalah seorang perwira polisi pemula, bekerja di sebuah pos polisi. Dia adalah orang yang jujur ​​dan berusaha untuk mencapai keadilan. Dia menghadapi seorang pembunuh psikopat, yang membuat seluruh bangsa ketakutan. Kehidupan Jung Ba-Reum berubah total setelahnya',
                'show_date' => 'Mar 3, 2021 - May 19, 2021',
                'duration' => ' 1 hr. 15 min.',
                'director' => 'Choi Joon Bae, Kang Cheol Woo',
                'artist' => 'Ahn Jae Wook, Kyung Soo Jin, Lee Hee Joon, Lee Seung Gi, Park Joo Hyun, Woo Ji Hyun',
                'episode' => 20,
                'slug' => 'mouse',
                'image' => 'https://i.mydramalist.com/XNeKO_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Shooting Star',
            'description' => '‘Shooting Stars’ menggambarkan hubungan cinta dan benci antara aktor top Gong Tae Sung (Kim Young Dae) dan pemimpin tim PR dari agensinya Oh Han Byeol (Lee Sung Kyung). Bintang top Gong Tae Sung dikenal luas oleh publik sebagai aktor yang baik dan baik hati, tetapi rewel dan sulit untuk menyenangkan di luar kamera. Meskipun Gong Tae Sung mempersulit Oh Han Byeol, keduanya mulai mengembangkan perasaan satu sama lain.',
                'show_date' => ' Apr 22, 2022 - Jun 11, 2022',
                'duration' => '60 min.',
                'director' => 'Lee Soo Hyun',
                'artist' => 'Kim Yoon Hye, Kim Young Dae, Lee Jung Shin, Lee Sung Kyung, Park So Jin, Yoon Jong Hoon',
                'episode' => 16,
                'slug' => 'shooting-star',
                'image' => 'https://i.mydramalist.com/BAwvb_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'The Sound Of Magic',
            'description' => 'Yoon A-Yi (Choi Sung-Eun) adalah seorang siswa sekolah menengah, tetapi dia mendukung dirinya sendiri dan adik perempuannya dengan bekerja paruh waktu. Dia tidak tahu di mana orang tuanya. Ayahnya diusir dari rumah karena penagih utang dan ibunya kemudian meninggalkan rumah. Bahkan dengan situasi keuangannya yang buruk, dia mampu menduduki peringkat teratas di sekolahnya secara akademis.',
                'show_date' => 'May 6,2022',
                'duration' => '1 hr. 10 min.',
                'director' => 'Kim Seong Yoon',
                'artist' => 'Choi Sung Eun, Hong Jung Min, Hwang In Yeop, Ji Chang Wook, Ji Hye Won, Oh So Hyun',
                'episode' => 6,
                'slug' => 'the-sound-of-magic',
                'image' => 'https://i.mydramalist.com/djDkW_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Crazy Love',
                'description' => 'drama Korea romantis tahun 2022 yang menggambarkan hubungan antara instruktur matematika dan sekretarisnya. No Go Jin adalah seorang instruktur matematika brilian yang menjalankan institusi swastanya sendiri, GOTOP. Rupanya, dia tampak sosok yang sempurna dengan kecerdasan dan penampilan menawan. Namun, dia berpura-pura mengalami amnesia setelah seseorang berniat membunuhnya. Sementara itu, Lee Shin Ah adalah sekretaris No Go Jin dengan kepribadian introvert. Dia pendiam tapi bertanggung jawab. Sayangnya, dia tidak punya banyak waktu untuk hidup. Kemudian, dia berpura-pura menjadi tunangan Go Jin setelah dia tahu tentang amnesia Go Jin.',
                'show_date' => 'Mar 7, 2022 - Apr 26, 2022',
                'duration' => ' 1 hr. 5 min.',
                'director' => 'Kim Jung Hyun',
                'artist' => 'Ha Joon, Jo In, Kim Jae Wook, Krystal Jung, Yoo In Young, Yoon San Ha',
                'episode' => 16,
                'slug' => 'crazy-love',
                'image' => 'https://i.mydramalist.com/4848k_4f.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Sisyphus The Myth',
            'description' => 'Sebuah kisah perjalanan waktu antara seorang insinyur jenius Han Tae-Sul ( Cho Seung-Woo ) dan penyelamatnya dari masa depan Kang Seo-Hae ( Park Shin-Hye ).',
                'show_date' => ' Feb 17, 2021 - Apr 8, 2021',
                'duration' => ' 1 hr. 10 min.',
                'director' => 'Jin Hyeok',
                'artist' => 'Cho Seung Woo, Park Shin Hye. Heo Joon-Seok, Tae In Ho',
                'episode' => 16,
                'slug' => 'sisyphus-the-myth',
                'image' => 'https://i.mydramalist.com/Bym1q_4c.jpg',
                'created_at' => '2022-07-05 14:00:32',
                'updated_at' => '2022-07-08 07:34:55',
            ),
        ));
        
        
    }
}